name: Test workflow

on: push

# base
jobs:
  main_job:
    name: Main
    env:
      secret: ${{ secrets.SECRET }}
      VER: 5
    runs-on: ubuntu-18.04
    container: 
      image: centos:7

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Cache
        id: hello-cache
        uses: actions/cache@v2
        with:
          path: build-${{ env.VER }}/bb.1/hello.txt
          key: hello

      - name: cache main
        uses: actions/cache@v2
        with:
          path: build-${{ env.VER }}
          key: main-${{ env.VER }}

        # TODO add file main which appends and caches as build
        # add build/static which chaces independantly for not rebuilding
        # but how prevent rebuild in bash
      - name: create hello
        if: steps.hello-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p build
          mkdir -p build/ver-${{ env.VER }}
          mkdir -p build/static
          if [-f build/static/static.txt]
          then
            printf  "static\n%.0s" {1..5} > build/static/static.txt
          fi
          echo "HELLO\n" >> build/ver-${{ env.VER }}/hello.txt
          ls -al build/ver-${{ env.VER }}
      - name: upload hello
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact-hello1
          path: |
            build