name: Test workflow

on: push

# base
jobs:
  main_job:
    name: Main
    env:
      secret: ${{ secrets.SECRET }}
      VER: 5
    runs-on: ubuntu-18.04
    container: 
      image: centos:7

    steps:
      - name: install deps
        run: |
          yum -y install redhat-lsb-core 
          curl -O -L https://golang.org/dl/go1.15.3.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.15.3.linux-amd64.tar.gz
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Cache
        id: hello-cache
        uses: actions/cache@v2
        with:
          path: build-${{ env.VER }}/bb.1/hello.txt
          key: hello
      - name: create hello
        if: steps.hello-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p build-${{ env.VER }}/bb.1
          echo HELLO > build-${{ env.VER }}/bb.1/hello.txt
          ls -al build-${{ env.VER }}/bb.1
      - name: upload hello
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact-hello
          path: |
            build-${{ env.VER }}/bb.*/hello.txt
