name: Test workflow

on: push

# base
jobs:
  main_job:
    name: Main
    env:
      secret: ${{ secrets.SECRET }}
      VER: 5
    runs-on: ubuntu-18.04
    container: 
      image: centos:7

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: cache main
        uses: actions/cache@v2
        with:
          path: |
            build/
            !build/static/
          key: main-3

      - name: Show folders
        run: |
          ls -al
          ls -al build
          ls -al build/static
          cat build/ver-${{ env.VER }}/hello.txt

      - name: Cache static
        uses: actions/cache@v2
        with:
          path: build/static/*
          key: static-3

        # TODO add file main which appends and caches as build
        # add build/static which chaces independantly for not rebuilding
        # but how prevent rebuild in bash
      - name: create hello
        run: |
          mkdir -p build
          mkdir -p build/ver-${{ env.VER }}
          mkdir -p build/static
          ls -al build/ver-${{ env.VER }}
          ls -al build/static/
          if ! [ -f build/static/static.txt ];
          then
            printf  "static\n%.0s" {1..50} >> build/static/static.txt
          fi
          echo "HELLO" >> build/ver-${{ env.VER }}/hello.txt
          ls -al build/ver-${{ env.VER }}
      - name: upload hello
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact-hello1
          path: |
            build