name: Test workflow

on: push

# base
jobs:
  main_job:
    name: Main
    env:
      secret: ${{ secrets.SECRET }}
      VER: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos]
        include:
          - container: centos:7
            os: ubuntu-18.04

    steps:
      - name: install deps
        if: matrix.os == ubuntu-18.04
        run: |
          yum -y install redhat-lsb-core 
          curl -O -L https://golang.org/dl/go1.15.3.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.15.3.linux-amd64.tar.gz

      - name: install deps
        if: matrix.os == macos
        run: |
          brew install go

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_SECRET }}
          submodules: 'recursive'
      - name: run
        run: |
          export PATH=/usr/local/go/bin:$PATH
          go build main.go
          ./main
