name: Test workflow

on: push


# base
jobs:
  test:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: create files
        run: |
          echo b > b
          echo a > a
      - name: test multiline
        run: >
          cp
          b b1

          cp
          a a1
      - name:
        run: |
          cat a1
          cat a2
      
      - name: run on master
        if: github.ref == 'refs/heads/master'
        run: echo we are on master
