name: Test workflow

on: push


# base
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: imberfox/test-actions/base-img
          tag_with_ref: true
  # here is matrix if macOS don't use container
  run_go:
    name: run go
    needs: push_to_registry
    runs-on: ubuntu-18.04
    container: 
      image:  docker.pkg.github.com/imberfox/test-actions/base-img
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: run
        run: |
          pwd
          ls -al
          /usr/local/go/bin/go run main.go
