name: Test workflow

on: push

# base
jobs:
  main_job:
    name: Main
    env:
      secret: ${{ secrets.SECRET }}
      VER: 5
    runs-on: ubuntu-18.04
    container: 
      image: centos:7

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: cache main
        uses: actions/cache@v2
        with:
          path: |
            !~/build/static
            ~/build
          key: main-6

      - name: Show folders 1
        run: |
          ls -al
          ls -al ~/build


      - name: Cache static
        uses: actions/cache@v2
        with:
          path: ~/build/static
          key: static-6

      - name: Show folders 2
        run: |
          ls -al
          ls -al ~/build

      - name: create hello
        run: |
          mkdir -p ~/build
          mkdir -p ~/build/ver-${{ env.VER }}
          mkdir -p ~/build/static
          ls -al ~/build/ver-${{ env.VER }}
          ls -al ~/build/static/
          if ! [ -f ~/build/static/static.txt ];
          then
            printf  "static\n%.0s" {1..50} >> ~/build/static/static.txt
          fi
          echo "HELLO" >> ~/build/ver-${{ env.VER }}/hello.txt
          ls -al ~/build/ver-${{ env.VER }}
      - name: upload hello
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact-hello1
          path: |
            ~/build
