name: Test workflow

on: push


# base
jobs:
  test:
    name: Push Docker image to GitHub Packages
    runs-on: macos-10.15
    steps:
      - name: check python
        run: | 
          python -v
          python2 -v || echo 'No python2'

      - name: Init python 2
        run: brew install python@2